// Generated by CoffeeScript 1.4.0

/*
express - require 'express'
app = express.createServer()

app.get '/', (req, res) ->
  res.send "Hello World"
*/


(function() {

  exports.index = function(res, req) {
    return res.render('index', {
      title: index
    });
  };

}).call(this);
